### ISSUE TITLE
Peer to peer code review CSS changes.

### ISSUE THREAD

**Issue by angeluray** [LuisDavidRodriguez/Portfolio#11]
Hi Luis! You've done a great job so far, however, I think that it would be better if you add less **margin-bottom** to **"stories-info"** class to make your project more similar Figma template.

**Comment by tamana-Balkhi** [comment]
at all the code was clear and understandable so there are some issues that needed to be solves:
it will be better to add some margin left and right on welcome section  of mobile version in order to the text be centered.
